CLIENT_ID = 'k_ZnJdAJyM-NRNjOJhfJJw'
CLIENT_SECRET = 'zr3sjutLDNyEi6gFSd4eZ-gqAb9nUw'
PASSWORD = 'mcsx007A'
USERNAME = 'Fantastic-Apartment8'
USER_AGENT = 'android:com.example.myredditapp:v1.0.0 (by /u/Fantastic-Apartment8)'